import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { LabelBadge } from "./LabelBadge.js";

export interface VerdictMeta {
  markdown: string;
  model?: string;
  provider?: string;
  stub: boolean;
}

interface Props {
  verdict: VerdictMeta;
}

function shortAddr(addr: string): string {
  if (addr.length <= 14) return addr;
  return `${addr.slice(0, 8)}…${addr.slice(-4)}`;
}

export function VerdictPanel({ verdict }: Props) {
  const { markdown, model, provider, stub } = verdict;
  return (
    <section className="p-5 rounded-lg border border-slate-700 bg-slate-900/50">
      <header className="flex items-center justify-between gap-2 pb-3 border-b border-slate-800">
        <div>
          <h2 className="text-xs uppercase tracking-wider text-slate-500">
            Verdict
          </h2>
          {model && (
            <p className="mt-1 text-[10px] font-mono text-slate-500">
              {model}
              {provider && provider !== "stub" && (
                <span className="ml-2 text-slate-600">
                  via {shortAddr(provider)}
                </span>
              )}
            </p>
          )}
        </div>
        <LabelBadge label={stub ? "EMULATED" : "ESTIMATED"} />
      </header>

      {stub && (
        <div
          role="alert"
          className="mt-3 rounded-md border border-orange-500/60 bg-orange-500/10 px-3 py-2 flex items-start gap-2"
        >
          <span aria-hidden className="text-orange-300 text-sm leading-5">⚠</span>
          <div className="text-[11px] leading-relaxed text-orange-200">
            <strong className="font-semibold uppercase tracking-wider text-[10px]">
              TEE unavailable — fallback verdict
            </strong>
            <p className="mt-0.5 text-orange-100/90">
              The 0G Compute broker did not return an attested verdict for
              this run. The text below is a deterministic stub generated
              client-side, not a TEE-attested inference. Configure
              {" "}<code className="text-orange-300/90">OG_COMPUTE_PRIVATE_KEY</code>{" "}
              with a funded broker ledger + provider sub-account to route
              through the real TEE provider.
            </p>
          </div>
        </div>
      )}

      <div className="mt-3 text-sm leading-relaxed text-slate-200 prose prose-invert prose-sm max-w-none">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
      </div>

      {markdown.includes("[unsupported]") && (
        <p className="mt-3 text-[10px] text-amber-300/90">
          <code>[unsupported]</code> = the AT-4 hallucination guard caught a
          number the model wrote that does not trace back to the report data,
          and masked it. The agent self-fact-checks before publishing — every
          $ / % / hex claim must round-trip the input JSON within ±2&nbsp;%.
        </p>
      )}

      {!stub && (
        <p className="mt-3 text-[10px] text-slate-500">
          Verdict generated by a TEE-attested 0G Compute provider. The
          provider's signed response is verifiable against its on-chain
          attestation report.
        </p>
      )}
    </section>
  );
}
